INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_username_check', '1');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'username_maxlength', '20');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'forbidden_names', 'administrator,moderator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'author_email', '2');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'author_homepage', '1'); 
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'comment_maxlength', '1000');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'comment_minlength', '0');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'word_maxlength', '15');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'link_maxlength', '30');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'flood_time', '30');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_notification', '0');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'notification_email', '');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'template', 'default');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_smiles', '1');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'comments_per_page', '10');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'comments_page_limit', '15');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'comments_pagination', 'both');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'comments_order', 'DESC');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'show_commentlength', '1');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_nested_quotes', '1');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_rss', '1');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'censor_replace_word', '[censored]');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'can_comment', 'Unregistered,Registered,Author,Editor,Publisher,Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'can_reply', 'Unregistered,Registered,Author,Editor,Publisher,Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'show_policy', 'Unregistered,Registered');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_captcha', 'Unregistered');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'floodprotection', 'Unregistered,Registered,Author,Editor');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_comment_length_check', 'Unregistered,Registered');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'autopublish', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'autolinkurls', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_subscribe', 'Unregistered,Registered,Author,Editor,Publisher,Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_gravatar', '');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'can_view_homepage', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'can_publish', 'Publisher,Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'can_view_email', 'Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'can_edit', 'Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'can_edit_own', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'can_delete', 'Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'can_delete_own', 'Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_bbcode_b', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_bbcode_i', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_bbcode_u', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_bbcode_s', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_bbcode_url', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_bbcode_img', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_bbcode_list', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_bbcode_hide', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'can_view_ip', 'Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_categories', '');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'emailprotection', 'Unregistered');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_comment_maxlength_check', '');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_autocensor', 'Unregistered');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'badwords', '');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'smiles', ':D	laugh.gif\n:lol:	lol.gif\n:-)	smile.gif\n;-)	wink.gif\n8)	cool.gif\n:-|	normal.gif\n:-*	whistling.gif\n:oops:	redface.gif\n:sad:	sad.gif\n:cry:	cry.gif\n:o	surprised.gif\n:-?	confused.gif\n:-x	sick.gif\n:eek:	shocked.gif\n:zzz	sleeping.gif\n:P	tongue.gif\n:roll:	rolleyes.gif\n:sigh:	unsure.gif');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_mambots', '1');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'form_show', '1');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'display_author', 'name');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_voting', '1');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'can_vote', 'Unregistered,Registered,Author,Editor,Publisher,Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'merge_time', '0');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'template_view', 'list');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'message_policy_post', '');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'message_policy_whocancomment', '');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'message_locked', 'This content has been locked. You can no longer post any comment.');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'comment_title', '0');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_custom_bbcode', '0');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_bbcode_quote', 'Unregistered,Registered,Author,Editor,Publisher,Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_bbcode_code', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_geshi', '0');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'can_report', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Administrator');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'enable_quick_moderation', '0');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'notification_type', '1,2');
INSERT INTO `#__jcomments_settings` VALUES ('', '', 'captcha_engine', 'kcaptcha');
