<?php
class JConfig {
	var $irdu_environment = 'Content Preview';
	var $irdu_version = '201';
	var $offline = '0';
	var $editor = 'tinymce';
	var $list_limit = '20';
	var $helpurl = 'http://help.joomla.org';
	var $debug = '0';
	var $debug_lang = '0';
	var $sef = '0';
	var $sef_rewrite = '0';
	var $sef_suffix = '0';
	var $feed_limit = '10';
	var $feed_email = 'author';
	var $secret =  '';#TODO-CONFIGURE
	var $gzip = '0';
	var $error_reporting = '-1';
	var $xmlrpc_server = '0';
	var $log_path = '/var/www/html/logs';
	var $tmp_path = '/var/www/html/tmp';
	var $live_site = '';
	var $force_ssl = '0';
	var $offset = '0';
	var $caching = '0';
	var $cachetime = '15';
	var $cache_handler = 'file';
	var $memcache_settings = array();
	var $ftp_enable = '1';
	var $ftp_host = '';
	var $ftp_port = '21';
	var $ftp_user = '';
	var $ftp_pass = '';
	var $ftp_root = '';
	var $dbtype = 'mysql';
	var $host =  '';#TODO-CONFIGURE
	var $user = '';#TODO-CONFIGURE
	var $db = 'DBJoomla';
	var $dbprefix = 'jos_';
	var $mailer = 'smtp';
	var $mailfrom = 'informaticslab@cdc.gov';
	var $fromname = 'CDC Informatics R&D';
	var $sendmail = '';
	var $smtpauth = '0';
	var $smtpsecure = 'none';
	var $smtpport = '25';
	var $smtpuser = '';
	var $smtppass = '';
	var $smtphost = 'smtp.lab.local';
	var $MetaAuthor = '1';
	var $MetaTitle = '1';
	var $lifetime = '15';
	var $session_handler = 'database';
	var $password = '';#TODO-CONFIGURE
	var $sitename = 'Informatics Research and Development Laboratory, Centers for Disease Control and Prevention';
	var $MetaDesc = 'Informatics Research and Development Laboratory, Centers for Disease Control and Prevention';
	var $MetaKeys = 'Informatics, Public Health, CDC, Centers for Disease Control and Prevention, Research, Development, Laboratory';
	var $offline_message = 'This site is down for maintenance. Please check back again soon.';
	var $legacy = '0';
	var $debug_db = '0';
	var $app_comments_user = '';#TODO-CONFIGURE
	var $app_comments_pass = '';#TODO-CONFIGURE
	var $app_lab_pass = '';#TODO-CONFIGURE
}
?>